--- 
title: "Lab book"
subtitle: "" 
author: "Nikolaos Tourvas"
date: "Last update on `r Sys.Date()`"
site: bookdown::bookdown_site
fontsize: 12pt
mainfont: Liberation Serif
linestretch: 1.15
geometry: margin=2.54cm
lof: yes
lot: yes
output: bookdown::gitbook
documentclass: report
bibliography: library.bib
# biblio-style: apalike
csl: apa.csl
link-citations: yes
description: "This is a minimal example of using the bookdown package to write a lab book. The output format for this example is bookdown::gitbook."
output_dir: "docs"
---

# index {-}
This is a minimal example of using the bookdown package to write a lab book. The output format for this example is bookdown::gitbook.

Test test.

# Protocols

Here is the repository of all protocols used in the experiments of this lab book.


## CTAB - ΕΚΕΤΑ {#CTAB}

### Introduction


### Materials

- CTAB
- β-mercaptoethanol
- Chloroform
- Isopropanol
- Sodium acetate
- 70% Ethanol
- TE
- RNAse

Η αιθανόλη πρέπει να αφαιρείται εντελώς γιατί είναι ενζυμικός αναστολέας  
β-merc: σπάει δεσμούς πρωτεϊνών που δε θέλουμε  
CTAB: λύει κύτταρα και τα βοηθά να διαλυθούν, απελευθερώνεται το DNA  
Οι οργανικοί διαλύτες (χλωροφόρμιο) διαλύουν το πλαστικό και ομογενοποιούνται με τα συστατικά του

### Procedure

1. Switch water bath on
2. Add __800μL CTAB__ and __10μL β-mercaptoethanol__
3. Place samples at __65°C__ for __30'__ (shake vigorously at 15') (while waiting prepare the tubes needed)
4. Short centrifuge __7000rpm 10'__ and collect the clear liquid
5. Add __800μl Chloroform__
6. Spin at __7000 rpm 20'__
7. Take top phase in a new tube
8. Repeat steps 5 and 6 (twice, optional)
9. Add __2/3 of the volume isopropanol__ (final tubes) and __1/10 sodium acetate__ and vortex
10. Place at __-20°C__ O.N. (18 hours)
11. Spin at max (__16000 rpm__) for __10'__ and throw away the supernant
12. Wash with __70% Ethanol (1ml)__ and spin at __14000 rpm__ for __10'__
13. Repeat step 12 after the tube has dried
14. Spin short (__16000 rpm for 10'__)
15. Add __1xTE__ (__100μl or 70μl__) and __2μl RNAse__ (10μg/μl) (pipeting until pellet is dissolved)
16. Incubate at __37°C__ for __30'__ - __1h__ until pellet is dissolved 


# Inventory

## Oligos

## PCR Reagents
If a "ready-to-go" master mix is provided, make aliquotes of it.

## Other Reagents
### ddH~2~O
#### 2018-11-19 {#w20181119}
four new tubes 

### apionismeno H~2~O


# Lab book

## Abies SNPs {#snp}
### 2018-11-18 {#experiment1}

Σημερινό πείραμα
φξκωβξφρω
οπξβιρφηνβιοτρφην

ιοωβφοιτηβρτη
ονβιρφνβρ4


### 2018-11-19

αποτέλεσμα πειράματος \@ref(experiment1)



## Aa experiment
### 2018-11-20
this is a test
jbijbnujn

jkljnknjokn'on

khiofhoidhc

jnvnrvhnriovbr

vrkfnvbiorhnbior

voirfbvuier


### 2018-11-20
PCR using water \@ref(w20181119)


# References
